### ISSUE TITLE
server side rendering, getting document is not defined error

### ISSUE THREAD

**Issue by hamed-farag** [spyip/react-film#28]
Hello,

Trying to use this library with server-side rendering, but I am getting a "document is not defined error".
![image](https://user-images.githubusercontent.com/5382471/61877432-4a641300-aeef-11e9-960a-bd71a18e2e9c.png)

**Comment by giulianok** [comment]
@hamed-farag found the issue and I made a PR https://github.com/spyip/react-film/pull/29.

Also, for a quick fix, you can import the components directly (e.g. `import FilmStrip from 'react-film/lib/FilmStrip';`)

**Comment by hamed-farag** [comment]
@giulianok your pull request merged 🎉 🎉

**Comment by Tellenn** [comment]
Hi, I'm very interested by this fix.

When do you think you'll release this ?

Thanks.
