### ISSUE TITLE
RTL carousel broken

### ISSUE THREAD

**Issue by corinagum** [spyip/react-film#75]
https://spyip.github.io/react-film/ second carousel

- `<` flipper never shows
- If navigating the carousel by tab, the carousel will jump from left all the way to right after a few seconds

Sorry for the inaccurate screencapture... :( For some reason when I try to record, recording never happens where I specify it to (note the red dotted line...)

https://user-images.githubusercontent.com/14900841/114793602-8e402100-9d3f-11eb-981f-e9aa77ed23e0.mp4

**Comment by compulim** [comment]
This is related to a bug in Chrome, https://www.chromestatus.com/feature/5759578031521792.

The previous version of `react-film` workaround-ed the bug. And Chrome 85+ fixed that bug, which need to have the workaround removed.
